"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import schemaupdaterequest as shared_schemaupdaterequest
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from fivetran import utils
from typing import Optional

class StandardConfigUpdateRequestSchemaChangeHandlingEnum(str, Enum):
    r"""The possible values for the schema_change_handling parameter are as follows: <br /> ALLOW_ALL - all new schemas, tables, and columns which appear in the source after the initial setup are included in syncs <br /> ALLOW_COLUMNS - all new schemas and tables which appear in the source after the initial setup are excluded from syncs, but new columns are included <br /> BLOCK_ALL - all new schemas, tables, and columns which appear in the source after the initial setup are excluded from syncs"""
    ALLOW_ALL = "ALLOW_ALL"
    ALLOW_COLUMNS = "ALLOW_COLUMNS"
    BLOCK_ALL = "BLOCK_ALL"


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class StandardConfigUpdateRequest:
    
    schema_change_handling: Optional[StandardConfigUpdateRequestSchemaChangeHandlingEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('schema_change_handling'), 'exclude': lambda f: f is None }})
    r"""The possible values for the schema_change_handling parameter are as follows: <br /> ALLOW_ALL - all new schemas, tables, and columns which appear in the source after the initial setup are included in syncs <br /> ALLOW_COLUMNS - all new schemas and tables which appear in the source after the initial setup are excluded from syncs, but new columns are included <br /> BLOCK_ALL - all new schemas, tables, and columns which appear in the source after the initial setup are excluded from syncs"""  
    schemas: Optional[dict[str, shared_schemaupdaterequest.SchemaUpdateRequest]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('schemas'), 'exclude': lambda f: f is None }})
    r"""The set of schemas within your connector schema config that are synced into the destination"""  
    